#!/bin/sh

pdnsutil create-zone $1.arne-jansen.sb.uclllabs.be
pdnsutil clear-zone $1.arne-jansen.sb.uclllabs.be
pdnsutil add-record testing.arne-jansen.sb.uclllabs.be . SOA 'ns.arne-jansen.sb.uclllabs.be hostmaster.arne-jansen.sb.uclllabs.be 2020111621 1200 120 1209600 720'
pdnsutil add-record testing.arne-jansen.sb.uclllabs.be ns NS 3600 193.191.177.135
