#!/bin/sh

TFLAG="$1"
echo $TFLAG

if [ $TFLAG = "-t" ]; 
then
	case $2 in
	A)
		echo "pdnsutil add-record $5 $3 $2 3600 $4"
		break
		;;
	CNAME)
		echo "See you again!"
		break
		;;
	MX)
		echo "Sorry, I don't understand"
		break
		;;

  esac

else
	echo "pdnsutil add-record $3 $1 A 3600 $2" 
fi
