#!/bin/bash


SUBDOMAIN=$(echo $1 | cut -d"." -f1)
DOCROOTS=/var/www/html/
APACHEROOT=/etc/apache2
LOGROOT=/var/log/apache2/vhostlogs/$SUBDOMAIN/error.log
VHOSTFILE=$APACHEROOT/sites-available/$SUBDOMAIN
mkdir $DOCROOTS$SUBDOMAIN
touch $DOCROOTS$SUBDOMAIN/index.html
echo 'welcome '$SUBDOMAIN > $DOCROOTS$SUBDOMAIN/index.html
cp $APACHEROOT/template $VHOSTFILE

ELOG="\/var\/log\/apache2\/vhostlogs\/$SUBDOMAIN\/error.log"
EHOST="\/var\/www\/html\/$SUBDOMAIN"
sed -i "s/^ServerName/ServerName $SUBDOMAIN.arne-jansen.sb.uclllabs.be/g" $VHOSTFILE
sed -i "s/^DocumentRoot/DocumentRoot $EHOST/g" $VHOSTFILE
sed -i "s/^ErrorLog/ErrorLog $ELOG/g" $VHOSTFILE
